# Generated by Django 5.2.15 on 2026-06-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_webauthn', '0002_alter_webauthndevice_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthndevice',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
